from pymongo import MongoClient
from database.models import Customer
import os
from dotenv import load_dotenv

load_dotenv()

MONGODB_URI = os.getenv("MONGODB_URI")
DB_NAME = "loan_system"
client = MongoClient(MONGODB_URI)
db = client[DB_NAME]
collection = db['customers']

customers = [
    {
        "customer_id": "CUST001",
        "name": "Aarav Mehta",
        "phone": "9876543210",
        "email": "aarav.mehta@gmail.com",
        "address": "Sector 45",
        "city": "Gurugram",
        "state": "Haryana",
        "pincode": "122003",
        "date_of_birth": "1999-05-12",
        "age": 25,
        "monthly_income": 75000,
        "employment_status": "employed",
        "employer_name": "Infosys",
        "credit_score": 780,
        "existing_loan_amount": 200000,
        "existing_loan_type": "personal",
        "pre_approved_limit": 800000,
        "kyc_verified": False
    },
    {
        "customer_id": "CUST002",
        "name": "Riya Sharma",
        "phone": "9123456789",
        "email": "riya.sharma@gmail.com",
        "address": "DLF Phase 3",
        "city": "Gurugram",
        "state": "Haryana",
        "pincode": "122002",
        "date_of_birth": "2001-02-18",
        "age": 23,
        "monthly_income": 42000,
        "employment_status": "employed",
        "employer_name": "TCS",
        "credit_score": 720,
        "existing_loan_amount": 0,
        "existing_loan_type": None,
        "pre_approved_limit": 300000,
        "kyc_verified": False
    },
    {
        "customer_id": "CUST003",
        "name": "Mohit Verma",
        "phone": "9988776655",
        "email": None,
        "address": "Indiranagar",
        "city": "Bengaluru",
        "state": "Karnataka",
        "pincode": "560038",
        "date_of_birth": "1995-11-08",
        "age": 29,
        "monthly_income": 110000,
        "employment_status": "self-employed",
        "employer_name": None,
        "credit_score": 810,
        "existing_loan_amount": 500000,
        "existing_loan_type": "business",
        "pre_approved_limit": 1200000,
        "kyc_verified": False
    },
    {
        "customer_id": "CUST004",
        "name": "Sneha Iyer",
        "phone": "9012345678",
        "email": "sneha.iyer@gmail.com",
        "address": "Adyar",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "pincode": "600020",
        "date_of_birth": "1998-07-21",
        "age": 26,
        "monthly_income": 65000,
        "employment_status": "employed",
        "employer_name": "Zoho",
        "credit_score": 760,
        "existing_loan_amount": 150000,
        "existing_loan_type": "education",
        "pre_approved_limit": 600000,
        "kyc_verified": False
    },
    {
        "customer_id": "CUST005",
        "name": "Kunal Singh",
        "phone": "9345678123",
        "email": "kunal.singh@gmail.com",
        "address": "Andheri West",
        "city": "Mumbai",
        "state": "Maharashtra",
        "pincode": "400058",
        "date_of_birth": "1992-03-10",
        "age": 32,
        "monthly_income": 98000,
        "employment_status": "employed",
        "employer_name": "Reliance",
        "credit_score": 740,
        "existing_loan_amount": 300000,
        "existing_loan_type": "home",
        "pre_approved_limit": 900000,
        "kyc_verified": False
    },
    {
        "customer_id": "CUST006",
        "name": "Neha Gupta",
        "phone": "9090909090",
        "email": None,
        "address": "Civil Lines",
        "city": "Jaipur",
        "state": "Rajasthan",
        "pincode": "302006",
        "date_of_birth": "2000-12-05",
        "age": 24,
        "monthly_income": 30000,
        "employment_status": "student",
        "employer_name": None,
        "credit_score": 680,
        "existing_loan_amount": 50000,
        "existing_loan_type": "education",
        "pre_approved_limit": 150000,
        "kyc_verified": False
    },
    {
        "customer_id": "CUST007",
        "name": "Rajesh Khanna",
        "phone": "9811122233",
        "email": "rajesh.khanna@gmail.com",
        "address": "Aliganj",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "pincode": "226024",
        "date_of_birth": "1970-06-15",
        "age": 54,
        "monthly_income": 55000,
        "employment_status": "retired",
        "employer_name": None,
        "credit_score": 700,
        "existing_loan_amount": 0,
        "existing_loan_type": None,
        "pre_approved_limit": 250000,
        "kyc_verified": False
    },
    {
        "customer_id": "CUST008",
        "name": "Ananya Roy",
        "phone": "9876501234",
        "email": "ananya.roy@gmail.com",
        "address": "Salt Lake",
        "city": "Kolkata",
        "state": "West Bengal",
        "pincode": "700091",
        "date_of_birth": "1997-09-30",
        "age": 27,
        "monthly_income": 58000,
        "employment_status": "employed",
        "employer_name": "Cognizant",
        "credit_score": 750,
        "existing_loan_amount": 100000,
        "existing_loan_type": "personal",
        "pre_approved_limit": 500000,
        "kyc_verified": False
    },
    {
        "customer_id": "CUST009",
        "name": "Vikas Patel",
        "phone": "9765432109",
        "email": "vikas.patel@gmail.com",
        "address": "Navrangpura",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pincode": "380009",
        "date_of_birth": "1988-01-19",
        "age": 36,
        "monthly_income": 85000,
        "employment_status": "self-employed",
        "employer_name": None,
        "credit_score": 790,
        "existing_loan_amount": 400000,
        "existing_loan_type": "business",
        "pre_approved_limit": 1000000,
        "kyc_verified": False
    },
    {
        "customer_id": "CUST010",
        "name": "Pooja Nair",
        "phone": "9001234567",
        "email": "pooja.nair@gmail.com",
        "address": "Vyttila",
        "city": "Kochi",
        "state": "Kerala",
        "pincode": "682019",
        "date_of_birth": "1996-04-14",
        "age": 28,
        "monthly_income": 62000,
        "employment_status": "employed",
        "employer_name": "EY",
        "credit_score": 770,
        "existing_loan_amount": 180000,
        "existing_loan_type": "personal",
        "pre_approved_limit": 650000,
        "kyc_verified": False
    }
]

if __name__ == "__main__":
    collection.delete_many({})  # optional: clear collection
    collection.insert_many(customers)
    print("✅ 10 customers seeded successfully")
